name: Vavoo Liste Guncelle
on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Yazma izni için bu blok kritik
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Gereksinimleri Yukle
        run: pip install requests
      - name: Listeyi Olustur
        run: python main.py
      - name: Github'a Gonder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vavoo_to_list.m3u
          # Değişiklik yoksa hata vermemesi için || true ekledik
          git commit -m "Liste Guncellendi: $(date)" || exit 0
          git push
          
